[project]
name = "wordlebot"
version = "0.1.0"
description = "Basic wordle bot based on entropy optimization."
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "nbformat>=5.10.4",
    "nltk>=3.9.1",
    "numba>=0.61.2",
    "numpy==2.2.6",
    "plotly>=6.2.0",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
    "wordfreq>=3.1.1",
]
